export interface User {
  id: number;
  valid: boolean;
  userModId: number;
  dateMod: string;
  user: {
    id: number;
    valid: boolean;
    userModId: number;
    dateMod: string;
    code: number;
    username: string;
    ldapAccount: string;
    ldapCommonName: string;
    securityProfile: {
      id: number;
      valid: boolean;
      userModId: number;
      dateMod: string;
      literalDescriptionText: string;
    };
    individual: {
      id: number;
      valid: boolean;
      userModId: number;
      dateMod: string;
      type: string;
      name: string;
      surname: string;
      identificationTypeId: number;
      documentNumber: string;
      conflictive: boolean;
      conflictDescription: string;
      observations: string | null;
      nationalityId: number;
      countryId: number;
      languageId: number;
      paymentMethodId: number | null;
      relationCrId: number | null;
      client: boolean;
      subscriber: boolean;
      adverse: boolean;
      lopd: boolean;
      addresses: Array<{
        id: number;
        valid: boolean;
        userModId: number;
        dateMod: string;
        addressType: string | null;
        foreignAddress: boolean;
        street: string;
        postalCode: string | null;
        foreignPostalCode: string | null;
        foreignMunicipality: string | null;
        foreignProvince: string | null;
        foreignCountry: string | null;
      }>;
      emails: Array<any>;
      defaultEmail: string | null;
      phones: Array<any>;
      defaultPhone: string | null;
      bankAccounts: Array<any>;
      seguridadSocialNumber: string;
      birthDate: string;
      birthPlace: string | null;
      deathDate: string | null;
      maritalStatusId: number | null;
      latePayment: string | null;
      latePaymentDescription: string | null;
      fatherName: string | null;
      motherName: string | null;
      subscriberAntiquity: string | null;
      accountingAccount: string | null;
      genderId: number;
      profileId: number | null;
      attorneyId: number | null;
      expertId: number | null;
      judgeId: number | null;
      lawyerId: number | null;
      professionalId: number | null;
      tutorId: number | null;
      contactPersons: Array<any>;
      hasLegalRepresentatives: boolean;
      hasSpouse: boolean;
    };
    groups: Array<any>;
    offices: Array<any>;
    phone: string | null;
    email: string | null;
    personalization: string | null;
  };
  avatar: {
    id: number;
    valid: boolean;
    userModId: number;
    dateMod: string;
    filePath: string;
    fileName: string;
    originalFileName: string;
    mediaType: string;
    file: string | null;
    extension: string;
  } | null;
  language: {
    id: number;
    valid: boolean;
    userModId: number;
    dateMod: string;
    code: string;
    literalDescriptionText: string;
    active: boolean;
    interfície: boolean;
  };
  darkMode: number;
  accessibilityLevel: number;
  activateIndividual360: boolean;
  emailCopy: boolean;
  openCalendarNotifications: boolean;
}
